"""add difficulty_score to sub_task

Revision ID: 1b88d35a577b
Revises: 622d43fac804
Create Date: 2025-07-30 16:12:43.868387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b88d35a577b'
down_revision: Union[str, Sequence[str], None] = '622d43fac804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_task', sa.Column('difficulty_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_task', 'difficulty_score')
    # ### end Alembic commands ###
