"""add_product_type_fields_to_client_and_ticket

Revision ID: 37e4a1531f9d
Revises: a6839cb1db94
Create Date: 2025-09-07 16:06:46.660020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e4a1531f9d'
down_revision: Union[str, None] = 'a6839cb1db94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 首先创建ProductType表（如果不存在）
    # 检查表是否已存在，如果不存在则创建
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    if 'product_type' not in inspector.get_table_names():
        op.create_table('product_type',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
        
        # 2. 插入初始产品类型数据（与populate_data.py保持一致）
        product_types_data = [
            ('文具', 1), ('家电', 2), ('服装', 3), ('鞋类', 4), 
            ('家具', 5), ('厨具', 6), ('饰品', 7), ('食品', 8),
            ('箱包', 9), ('图书', 10), ('保健品', 11), ('情趣', 12),
            ('化妆品', 13), ('玩具', 14), ('床上用品', 15), 
            ('宠物用品', 16), ('其他', 999)
        ]
        
        for name, sort_order in product_types_data:
            op.execute(f"""
                INSERT INTO product_type (name, sort_order) 
                VALUES ('{name}', {sort_order})
            """)
    
    # 3. 添加client和ticket的新字段
    op.add_column('client', sa.Column('product_type_ids', sa.ARRAY(sa.Integer()), nullable=False, server_default='{}'))
    op.add_column('ticket', sa.Column('product_type_id', sa.Integer(), nullable=True))
    op.add_column('ticket', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.add_column('ticket', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    
    # 4. 创建外键约束
    op.create_foreign_key(None, 'ticket', 'product_type', ['product_type_id'], ['id'])
    
    # 注意：暂时保留 client.product_type 字段，数据迁移后再删除
    # op.drop_column('client', 'product_type')  # 将在数据迁移脚本中删除
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 查找并删除ticket表中指向product_type的外键约束
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    foreign_keys = inspector.get_foreign_keys('ticket')
    
    for fk in foreign_keys:
        if fk['referred_table'] == 'product_type' and fk['name']:
            op.drop_constraint(fk['name'], 'ticket', type_='foreignkey')
            break
    op.drop_column('ticket', 'price')
    op.drop_column('ticket', 'product_name')
    op.drop_column('ticket', 'product_type_id')
    op.drop_column('client', 'product_type_ids')
    op.drop_table('product_type')
    # 注意：如果需要恢复product_type字段，请在数据迁移回滚后添加
    # op.add_column('client', sa.Column('product_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###