"""add need_shoot to ticket

Revision ID: 3b3919600119
Revises: 1b88d35a577b
Create Date: 2025-08-01 14:12:17.247229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3919600119'
down_revision: Union[str, Sequence[str], None] = '1b88d35a577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('need_shoot', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'need_shoot')
    # ### end Alembic commands ###
