"""Add watermark field to tickets

Revision ID: 8c2ac534ee1f
Revises: 1152b85641ff
Create Date: 2025-08-11 15:13:42.273027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2ac534ee1f'
down_revision: Union[str, Sequence[str], None] = '1152b85641ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('need_watermark', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'need_watermark')
    # ### end Alembic commands ###
