"""add file_resource_id to contract

Revision ID: a6839cb1db94
Revises: 5ec78355fbe8
Create Date: 2025-09-04 17:11:37.992262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a6839cb1db94'
down_revision: Union[str, Sequence[str], None] = '5ec78355fbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('file_resource_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_contract_file_resource', 'contract', 'file_resource', ['file_resource_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_contract_file_resource_id', 'contract', ['file_resource_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contract_file_resource', 'contract', type_='foreignkey')
    op.drop_constraint('uq_contract_file_resource_id', 'contract', type_='unique')
    op.drop_column('contract', 'file_resource_id')
    # ### end Alembic commands ###
