"""Initial migration

Revision ID: cc3114500fcf
Revises: d7043c0951e3
Create Date: 2025-07-28 13:54:16.983536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3114500fcf'
down_revision: Union[str, Sequence[str], None] = 'd7043c0951e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_task', sa.Column('estimated_completion_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_task', 'estimated_completion_time')
    # ### end Alembic commands ###
